---
- hosts: all
  tasks:

    - name: Create Let's Encrypt directory
      file: { path: '/etc/letsencrypt/', state: directory }
      become: true

    - name: Create Let's Encrypt log directory
      file: { path: '/var/log/letsencrypt/', state: directory }
      become: true

    - name: Stop router
      docker_container: { name: router, state: stopped }

    - name: Update certificates
      with_items: '{{ certbot_domains }}'
      docker_container:
        name: certbot
        image: certbot/certbot
        published_ports: [ '80:80', '443:443' ]
        command: certonly --standalone --non-interactive --agree-tos -m {{certbot_email}} -d {{item}}
        volumes: [ '/etc/letsencrypt/', '/var/log/letsencrypt/' ]
      register: result

    - debug:
        var: result

    - name: Stop certbot
      docker_container: { name: certbot, state: stopped }

    - name: Start router
      docker_container: { name: router, state: started }
