---
- hosts: all
  tasks:

    - name: Create Let's Encrypt directory
      file: { path: '/etc/letsencrypt/', state: directory }
      become: true

    - name: Stop router
      docker_container: { name: router, state: stopped }

    - name: Update certificates
      docker_container:
        name: certbot
        image: certbot/certbot
        auto_remove: yes
        command: certonly --standalone --non-interactive --agree-tos -m {{ certbot_email }} -d {{ item }}
      loop: {{ certbot_domains }}

    - name: Start router
      docker_container: { name: router, state: started }
