---
- hosts: all
  tasks:

    - name: Project setup and update
      git:
        repo: https://github.com/javanile/report-ci.git
        dest: '{{ working_dir }}'
        version: master
        force: yes

    - name: Creates directory
      file: { path: '/etc/nginx/conf.d/', state: directory }
      become: true

    - name: Creates directory
      file: { path: '/var/log/nginx/', state: directory }
      become: true

    - name: Creates directory
      file: { path: '/etc/letsencrypt/', state: directory }
      become: true

    - name: Copy router config
      command: cp env/{{ inventory_hostname }}/report-ci.conf /etc/nginx/conf.d/
      args: { chdir: '{{ working_dir }}' }
      become: true

    - name: Create a network
      docker_network:
        name: router

    - name: Run `docker-compose up` again
      docker_service:
        project_src: '{{ working_dir }}'
        build: no
      register: output

    - debug:
        var: output

    - name: Router
      docker_container:
        name: router
        recreate: true
        image: nginx
        published_ports: [ '80:80', '443:443' ]
        networks: [{ name: router }]
        volumes:
          - /etc/nginx/conf.d/:/etc/nginx/conf.d/
          - /var/log/nginx/:/var/log/nginx/
          - /etc/letsencrypt/:/etc/letsencrypt/

