version: '3.7'

services:
  report-ci:
    build: ./
    networks:
      router:
        aliases:
          - report-ci
    volumes:
      - ./:/var/www/html

networks:
  router:
    external:
      name: internet